# permissions for end users to edit clusterupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterupgrade-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clusterupgrade-operator
    app.kubernetes.io/part-of: clusterupgrade-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterupgrade-editor-role
rules:
- apiGroups:
  - cluster.aruba.it
  resources:
  - clusterupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.aruba.it
  resources:
  - clusterupgrades/status
  verbs:
  - get
