---
- name: update kubelet config
  command: "sed -i 's/--register-node=false//' /etc/default/kubelet"
  when: not upgraded

- name: Test for line
  shell: grep -qxF ' --register-node=false' /etc/default/kubelet || echo ' --register-node=false' >> /etc/default/kubelet
  when: upgraded

- name: reload config
  command: systemctl daemon-reload

- name: restart kubelet
  command: systemctl restart kubelet.service
