 
- hosts: localhost
  tasks:
  - name: create the nodes list
    ansible.builtin.add_host:
      name: '{{ item }}'
      groups: nodes
      ansible_private_key_file: /opt/ansible/roles/clusterupgrade/files/test-key
      ansible_ssh_user: root
    loop: "{{ nodes_ip }}"

- hosts: nodes
  gather_facts: false
  roles:
    - clusterupgrade